name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  pages: write      
  id-token: write   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload Page as artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
